name: aurex-dev
services:
  db:
    image: postgres:15-alpine@sha256:f7d23353e1b15400d22ebe31189f4d314b87a4c129cc400c8c2d8d4ca127bf81
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:?run local-config}
    ports: ['127.0.0.1:54322:5432']
    volumes:
      - aurex-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/00-aurex.sql:ro
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -U postgres']
      interval: 2s
      timeout: 3s
      retries: 30
  auth:
    image: ghcr.io/supabase/gotrue:v2.197.0@sha256:1736a63078f5922b198c4cbe50f80ab9a2d3b54fe8b7b6cfb2e9dc5dbbc12c6b
    depends_on:
      db: { condition: service_healthy }
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: http://127.0.0.1:54321
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${DB_PASSWORD}@db:5432/postgres?sslmode=disable
      GOTRUE_DB_NAMESPACE: auth
      GOTRUE_SITE_URL: http://127.0.0.1:3000
      GOTRUE_URI_ALLOW_LIST: http://127.0.0.1:3000/**
      GOTRUE_DISABLE_SIGNUP: 'true'
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_EXTERNAL_EMAIL_ENABLED: 'true'
      GOTRUE_MAILER_URLPATHS_INVITE: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /auth/v1/verify
      GOTRUE_MAILER_AUTOCONFIRM: 'true'
      GOTRUE_SMTP_HOST: mail
      GOTRUE_SMTP_PORT: 1025
      GOTRUE_SMTP_ADMIN_EMAIL: noreply@aurex.demo
      GOTRUE_MFA_TOTP_ENROLL_ENABLED: 'true'
      GOTRUE_MFA_TOTP_VERIFY_ENABLED: 'true'
  rest:
    image: ghcr.io/supabase/postgrest:v16.4@sha256:d155c6718ed9a9f990d159a2ab7c0a3f16944dbb6d0a0344557421042acfe0df
    depends_on:
      db: { condition: service_healthy }
    environment:
      PGRST_DB_URI: postgres://authenticator:${DB_PASSWORD}@db:5432/postgres
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
  gateway:
    image: ghcr.io/supabase/kong:2.8.1@sha256:1b53405d8680a09d6f44494b7990bf7da2ea43f84a258c59717d4539abf09f6d
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 'off'
      KONG_DNS_ORDER: LAST,A,CNAME
    volumes: ['./kong.yml:/etc/kong/kong.yml:ro']
    ports: ['127.0.0.1:54321:8000']
    depends_on: [auth, rest]
  mail:
    image: ghcr.io/supabase/mailpit:v1.31.3@sha256:ed9b00c609e77e99c79b93f1178255ebc271868920f2c69a8d166bd5634ed10d
    ports: ['127.0.0.1:54324:8025']
volumes:
  aurex-db:
