import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
const files = readdirSync('supabase/migrations')
  .filter((f) => /^\d+_.+\.sql$/.test(f))
  .sort();
const sections = [
  '-- AUREX: bootstrap for a NEW Supabase staging project only. No secrets or demo data.',
  '-- Generated by scripts/staging-sql.mjs; migrations remain the source of truth.',
  'begin;',
  'set local search_path = public, extensions;',
  `do $$ begin
    if to_regclass('public.organizations_internal') is not null then
      raise exception 'AUREX is already initialized. Do not rerun the initial setup.';
    end if;
  end $$;`,
  'create schema if not exists supabase_migrations;',
  'create table if not exists supabase_migrations.schema_migrations(version text primary key, statements text[], name text);',
  'alter table supabase_migrations.schema_migrations enable row level security;',
  'revoke all on supabase_migrations.schema_migrations from public, anon, authenticated;',
];
for (const file of files) {
  const [version, ...parts] = file.replace(/\.sql$/, '').split('_');
  const name = parts.join('_');
  sections.push(`-- Migration: ${file}`, readFileSync('supabase/migrations/' + file, 'utf8'));
  sections.push(
    `insert into supabase_migrations.schema_migrations(version,name) values('${version}','${name}');`,
  );
}
sections.push(
  "notify pgrst, 'reload schema';",
  'commit;',
  "select 'AUREX schema ready' as result;",
);
writeFileSync('docs/SETUP_DATABASE.sql', sections.join('\n\n') + '\n');
console.log(`Prepared ${files.length} migrations; no credentials or seed included.`);
