-- AUREX: bootstrap for a NEW Supabase staging project only. No secrets or demo data.

-- Generated by scripts/staging-sql.mjs; migrations remain the source of truth.

begin;

set local search_path = public, extensions;

do $$ begin
    if to_regclass('public.organizations_internal') is not null then
      raise exception 'AUREX is already initialized. Do not rerun the initial setup.';
    end if;
  end $$;

create schema if not exists supabase_migrations;

create table if not exists supabase_migrations.schema_migrations(version text primary key, statements text[], name text);

alter table supabase_migrations.schema_migrations enable row level security;

revoke all on supabase_migrations.schema_migrations from public, anon, authenticated;

-- Migration: 202610050001_foundation.sql

-- AUREX OS: PostgreSQL is the source of truth, not the browser.
create extension if not exists pgcrypto;
create type public.app_role as enum ('owner','operations','pm','analyst','field','sales','finance','client','auditor');
create table public.organizations_internal (id uuid primary key default gen_random_uuid(), name text not null, demo boolean not null default false, created_at timestamptz not null default now());
create table public.memberships (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, user_id uuid not null references auth.users, role public.app_role not null, active boolean not null default true, created_at timestamptz not null default now(), unique(tenant_id,user_id));
create table public.project_members (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, user_id uuid not null references auth.users, unique(project_id,user_id));
create table public.permissions (role public.app_role not null, domain text not null, can_write boolean not null, primary key(role,domain));
insert into public.permissions
select r::public.app_role,d,w from (values
('owner','crm',true),('owner','projects',true),('owner','work',true),('owner','finance',true),('owner','research',true),('owner','marketing',true),('owner','data',true),('owner','files',true),('owner','admin',true),
('operations','crm',false),('operations','projects',true),('operations','work',true),('operations','research',true),('operations','files',true),
('pm','projects',true),('pm','work',true),('pm','research',true),('pm','files',true),
('analyst','projects',false),('analyst','work',true),('analyst','research',true),('analyst','files',true),
('field','projects',false),('field','work',true),('field','research',true),
('sales','crm',true),('sales','projects',false),('sales','marketing',true),('sales','files',true),
('finance','projects',false),('finance','work',false),('finance','finance',true),('finance','files',true),
('client','projects',false),('client','files',false),
('auditor','crm',false),('auditor','projects',false),('auditor','work',false),('auditor','finance',false),('auditor','research',false),('auditor','marketing',false),('auditor','data',false),('auditor','files',false)
) p(r,d,w);
create function public.allowed(t uuid,d text,writing boolean default false) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.memberships m join public.permissions p on p.role=m.role where m.user_id=auth.uid() and m.tenant_id=t and m.active and p.domain=d and (not writing or p.can_write) and (m.role not in ('owner','finance') or coalesce(auth.jwt()->>'aal','aal1')='aal2'));
$$;
create function public.scoped(t uuid,p uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.memberships m where m.user_id=auth.uid() and m.tenant_id=t and m.active and (m.role in ('owner','operations','finance','sales','auditor') or exists(select 1 from public.project_members pm where pm.tenant_id=t and pm.project_id=p and pm.user_id=auth.uid())));
$$;
create table public.audit_events (id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.organizations_internal, actor_id uuid,entity text not null,record_id uuid not null,action text not null,old_data jsonb,new_data jsonb,created_at timestamptz not null default now());
create function public.audit_change() returns trigger language plpgsql security definer set search_path='' as $$
 begin
 insert into public.audit_events(tenant_id,actor_id,entity,record_id,action,old_data,new_data) values(coalesce(new.tenant_id,old.tenant_id),auth.uid(),tg_table_name,coalesce(new.id,old.id),tg_op,case when tg_op!='INSERT' then to_jsonb(old) end,case when tg_op!='DELETE' then to_jsonb(new) end);
 return coalesce(new,old); end;
$$;
create function public.touch_record() returns trigger language plpgsql set search_path='' as $$ begin new.updated_at=now(); if tg_op='INSERT' and auth.uid() is not null then new.created_by=auth.uid(); end if; return new; end; $$;

create table public.accounts (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, name text not null check(length(name)>1), sector text, relationship text not null default 'prospect' check(relationship in ('prospect','client','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.accounts(tenant_id,created_at);
alter table public.accounts enable row level security;
create trigger touch before insert or update on public.accounts for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.accounts for each row execute function public.audit_change();
create policy read_rows on public.accounts for select to authenticated using(public.allowed(tenant_id,'crm'));
create policy insert_rows on public.accounts for insert to authenticated with check(public.allowed(tenant_id,'crm',true));
create policy update_rows on public.accounts for update to authenticated using(public.allowed(tenant_id,'crm',true)) with check(public.allowed(tenant_id,'crm',true));

create table public.contacts (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, account_id uuid not null, name text not null, email text not null, consent boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.contacts(tenant_id,created_at);
alter table public.contacts enable row level security;
create trigger touch before insert or update on public.contacts for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.contacts for each row execute function public.audit_change();
create policy read_rows on public.contacts for select to authenticated using(public.allowed(tenant_id,'crm'));
create policy insert_rows on public.contacts for insert to authenticated with check(public.allowed(tenant_id,'crm',true));
create policy update_rows on public.contacts for update to authenticated using(public.allowed(tenant_id,'crm',true)) with check(public.allowed(tenant_id,'crm',true));
alter table public.contacts add foreign key(tenant_id,account_id) references public.accounts(tenant_id,id);

create table public.leads (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, account_id uuid not null, contact_id uuid not null, name text not null, source text not null, need text not null, owner_id uuid not null references auth.users, next_action text not null, status text not null default 'new' check(status in ('new','qualified','converted','lost')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.leads(tenant_id,created_at);
alter table public.leads enable row level security;
create trigger touch before insert or update on public.leads for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.leads for each row execute function public.audit_change();
create policy read_rows on public.leads for select to authenticated using(public.allowed(tenant_id,'crm'));
create policy insert_rows on public.leads for insert to authenticated with check(public.allowed(tenant_id,'crm',true));
create policy update_rows on public.leads for update to authenticated using(public.allowed(tenant_id,'crm',true)) with check(public.allowed(tenant_id,'crm',true));
alter table public.leads add foreign key(tenant_id,account_id) references public.accounts(tenant_id,id);
alter table public.leads add foreign key(tenant_id,contact_id) references public.contacts(tenant_id,id);

create table public.opportunities (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, lead_id uuid not null, account_id uuid not null, contact_id uuid not null, name text not null, service text not null, amount numeric(16,2) not null check(amount>0), currency text not null default 'MXN' check(currency in ('MXN','USD')), probability numeric(5,2) not null default 20 check(probability between 0 and 100), stage text not null default 'Qualified', owner_id uuid not null references auth.users, next_action text not null, close_date date not null, lost_reason text, unique(tenant_id,lead_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.opportunities(tenant_id,created_at);
alter table public.opportunities enable row level security;
create trigger touch before insert or update on public.opportunities for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.opportunities for each row execute function public.audit_change();
create policy read_rows on public.opportunities for select to authenticated using(public.allowed(tenant_id,'crm'));
create policy insert_rows on public.opportunities for insert to authenticated with check(public.allowed(tenant_id,'crm',true));
create policy update_rows on public.opportunities for update to authenticated using(public.allowed(tenant_id,'crm',true)) with check(public.allowed(tenant_id,'crm',true));
alter table public.opportunities add foreign key(tenant_id,lead_id) references public.leads(tenant_id,id);
alter table public.opportunities add foreign key(tenant_id,account_id) references public.accounts(tenant_id,id);
alter table public.opportunities add foreign key(tenant_id,contact_id) references public.contacts(tenant_id,id);

create table public.opportunity_stage_history (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, opportunity_id uuid not null, from_stage text, to_stage text not null, reason text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.opportunity_stage_history(tenant_id,created_at);
alter table public.opportunity_stage_history enable row level security;
create trigger touch before insert or update on public.opportunity_stage_history for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.opportunity_stage_history for each row execute function public.audit_change();
create policy read_rows on public.opportunity_stage_history for select to authenticated using(public.allowed(tenant_id,'crm'));
alter table public.opportunity_stage_history add foreign key(tenant_id,opportunity_id) references public.opportunities(tenant_id,id);

create table public.proposals (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, opportunity_id uuid not null, name text not null, scope text not null, amount numeric(16,2) not null check(amount>0), version integer not null default 1, approved boolean not null default false, valid_until date not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.proposals(tenant_id,created_at);
alter table public.proposals enable row level security;
create trigger touch before insert or update on public.proposals for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.proposals for each row execute function public.audit_change();
create policy read_rows on public.proposals for select to authenticated using(public.allowed(tenant_id,'crm'));
alter table public.proposals add foreign key(tenant_id,opportunity_id) references public.opportunities(tenant_id,id);

create table public.contracts (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, opportunity_id uuid not null, account_id uuid not null, name text not null, scope text not null, fee numeric(16,2) not null check(fee>0), currency text not null default 'MXN', unique(tenant_id,opportunity_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.contracts(tenant_id,created_at);
alter table public.contracts enable row level security;
create trigger touch before insert or update on public.contracts for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.contracts for each row execute function public.audit_change();
create policy read_rows on public.contracts for select to authenticated using(public.allowed(tenant_id,'crm'));
alter table public.contracts add foreign key(tenant_id,opportunity_id) references public.opportunities(tenant_id,id);
alter table public.contracts add foreign key(tenant_id,account_id) references public.accounts(tenant_id,id);

create table public.projects (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, opportunity_id uuid, account_id uuid not null, contract_id uuid, name text not null, owner_id uuid not null references auth.users, status text not null default 'active', currency text not null default 'MXN', fee numeric(16,2) not null check(fee>=0), budget numeric(16,2) not null check(budget>=0), costs_complete boolean not null default false, unique(tenant_id,opportunity_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.projects(tenant_id,created_at);
alter table public.projects enable row level security;
create trigger touch before insert or update on public.projects for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.projects for each row execute function public.audit_change();
create policy read_rows on public.projects for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,id));
create policy insert_rows on public.projects for insert to authenticated with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,id));
create policy update_rows on public.projects for update to authenticated using(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,id)) with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,id));
alter table public.projects add foreign key(tenant_id,opportunity_id) references public.opportunities(tenant_id,id);
alter table public.projects add foreign key(tenant_id,account_id) references public.accounts(tenant_id,id);
alter table public.projects add foreign key(tenant_id,contract_id) references public.contracts(tenant_id,id);

create table public.phases (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, name text not null, position integer not null check(position between 1 and 6), gate_criteria text not null, approved_at timestamptz, approved_by uuid references auth.users, unique(project_id,position), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.phases(tenant_id,created_at);
alter table public.phases enable row level security;
create trigger touch before insert or update on public.phases for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.phases for each row execute function public.audit_change();
create policy read_rows on public.phases for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
create policy insert_rows on public.phases for insert to authenticated with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
create policy update_rows on public.phases for update to authenticated using(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id)) with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
alter table public.phases add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.milestones (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, name text not null, due_date date not null, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.milestones(tenant_id,created_at);
alter table public.milestones enable row level security;
create trigger touch before insert or update on public.milestones for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.milestones for each row execute function public.audit_change();
create policy read_rows on public.milestones for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
create policy insert_rows on public.milestones for insert to authenticated with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
create policy update_rows on public.milestones for update to authenticated using(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id)) with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
alter table public.milestones add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.tasks (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, phase_id uuid, name text not null, owner_id uuid not null references auth.users, status text not null default 'todo' check(status in ('todo','doing','blocked','done')), priority text not null default 'normal', due_date date not null, estimated_hours numeric(8,2) not null default 0 check(estimated_hours>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.tasks(tenant_id,created_at);
alter table public.tasks enable row level security;
create trigger touch before insert or update on public.tasks for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.tasks for each row execute function public.audit_change();
create policy read_rows on public.tasks for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
create policy insert_rows on public.tasks for insert to authenticated with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
create policy update_rows on public.tasks for update to authenticated using(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id)) with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
alter table public.tasks add foreign key(tenant_id,phase_id) references public.phases(tenant_id,id);
alter table public.tasks add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.role_cost_rates (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, user_id uuid not null references auth.users, cost_per_hour numeric(12,2) not null check(cost_per_hour>=0), effective_from date not null, unique(tenant_id,user_id,effective_from), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.role_cost_rates(tenant_id,created_at);
alter table public.role_cost_rates enable row level security;
create trigger touch before insert or update on public.role_cost_rates for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.role_cost_rates for each row execute function public.audit_change();
create policy read_rows on public.role_cost_rates for select to authenticated using(public.allowed(tenant_id,'finance'));
create policy insert_rows on public.role_cost_rates for insert to authenticated with check(public.allowed(tenant_id,'finance',true));
create policy update_rows on public.role_cost_rates for update to authenticated using(public.allowed(tenant_id,'finance',true)) with check(public.allowed(tenant_id,'finance',true));

create table public.time_entries (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, task_id uuid not null, user_id uuid not null references auth.users, name text not null, minutes integer not null check(minutes>0 and minutes<=1440), billable boolean not null default true, work_date date not null, hourly_cost numeric(12,2) not null check(hourly_cost>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.time_entries(tenant_id,created_at);
alter table public.time_entries enable row level security;
create trigger touch before insert or update on public.time_entries for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.time_entries for each row execute function public.audit_change();
create policy read_rows on public.time_entries for select to authenticated using(public.allowed(tenant_id,'work') and public.scoped(tenant_id,project_id));
alter table public.time_entries add foreign key(tenant_id,task_id) references public.tasks(tenant_id,id);
alter table public.time_entries add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.project_budgets (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, name text not null, amount numeric(16,2) not null check(amount>=0), unique(project_id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.project_budgets(tenant_id,created_at);
alter table public.project_budgets enable row level security;
create trigger touch before insert or update on public.project_budgets for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.project_budgets for each row execute function public.audit_change();
create policy read_rows on public.project_budgets for select to authenticated using(public.allowed(tenant_id,'finance') and public.scoped(tenant_id,project_id));
alter table public.project_budgets add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.expenses (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, name text not null, amount numeric(16,2) not null check(amount>0), status text not null default 'pending' check(status in ('pending','approved','rejected')), spent_on date not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.expenses(tenant_id,created_at);
alter table public.expenses enable row level security;
create trigger touch before insert or update on public.expenses for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.expenses for each row execute function public.audit_change();
create policy read_rows on public.expenses for select to authenticated using(public.allowed(tenant_id,'finance') and public.scoped(tenant_id,project_id));
create policy insert_rows on public.expenses for insert to authenticated with check(public.allowed(tenant_id,'finance',true) and public.scoped(tenant_id,project_id));
create policy update_rows on public.expenses for update to authenticated using(public.allowed(tenant_id,'finance',true) and public.scoped(tenant_id,project_id)) with check(public.allowed(tenant_id,'finance',true) and public.scoped(tenant_id,project_id));
alter table public.expenses add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.invoices (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, account_id uuid not null, name text not null, subtotal numeric(16,2) not null check(subtotal>0), tax numeric(16,2) not null default 0 check(tax>=0), currency text not null default 'MXN', issued_on date not null, due_date date not null, status text not null default 'issued' check(status in ('issued','partial','paid')), check(due_date>=issued_on), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.invoices(tenant_id,created_at);
alter table public.invoices enable row level security;
create trigger touch before insert or update on public.invoices for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.invoices for each row execute function public.audit_change();
create policy read_rows on public.invoices for select to authenticated using(public.allowed(tenant_id,'finance') and public.scoped(tenant_id,project_id));
alter table public.invoices add foreign key(tenant_id,account_id) references public.accounts(tenant_id,id);
alter table public.invoices add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.payments (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, invoice_id uuid not null, name text not null, amount numeric(16,2) not null check(amount>0), paid_on date not null, method text not null, reference text not null, idempotency_key uuid not null, unique(tenant_id,idempotency_key), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.payments(tenant_id,created_at);
alter table public.payments enable row level security;
create trigger touch before insert or update on public.payments for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.payments for each row execute function public.audit_change();
create policy read_rows on public.payments for select to authenticated using(public.allowed(tenant_id,'finance') and public.scoped(tenant_id,project_id));
alter table public.payments add foreign key(tenant_id,invoice_id) references public.invoices(tenant_id,id);
alter table public.payments add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.notifications (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, user_id uuid not null references auth.users, name text not null, read_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.notifications(tenant_id,created_at);
alter table public.notifications enable row level security;
create trigger touch before insert or update on public.notifications for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.notifications for each row execute function public.audit_change();
create policy read_rows on public.notifications for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
create policy insert_rows on public.notifications for insert to authenticated with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
create policy update_rows on public.notifications for update to authenticated using(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id)) with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
alter table public.notifications add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.kpi_definitions (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, name text not null, code text not null, formula text not null, version integer not null default 1, owner text not null, frequency text not null, target numeric, thresholds jsonb not null default '{}', drilldown text not null, unique(tenant_id,code), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.kpi_definitions(tenant_id,created_at);
alter table public.kpi_definitions enable row level security;
create trigger touch before insert or update on public.kpi_definitions for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.kpi_definitions for each row execute function public.audit_change();
create policy read_rows on public.kpi_definitions for select to authenticated using(public.allowed(tenant_id,'finance'));
create policy insert_rows on public.kpi_definitions for insert to authenticated with check(public.allowed(tenant_id,'finance',true));
create policy update_rows on public.kpi_definitions for update to authenticated using(public.allowed(tenant_id,'finance',true)) with check(public.allowed(tenant_id,'finance',true));

create table public.risks (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, name text not null, probability integer not null check(probability between 1 and 5), impact integer not null check(impact between 1 and 5), owner_id uuid not null references auth.users, mitigation text not null, review_date date not null, status text not null default 'open', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.risks(tenant_id,created_at);
alter table public.risks enable row level security;
create trigger touch before insert or update on public.risks for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.risks for each row execute function public.audit_change();
create policy read_rows on public.risks for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
create policy insert_rows on public.risks for insert to authenticated with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
create policy update_rows on public.risks for update to authenticated using(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id)) with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
alter table public.risks add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.issues (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, name text not null, impact text not null, action text not null, resolution text, status text not null default 'open', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.issues(tenant_id,created_at);
alter table public.issues enable row level security;
create trigger touch before insert or update on public.issues for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.issues for each row execute function public.audit_change();
create policy read_rows on public.issues for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
create policy insert_rows on public.issues for insert to authenticated with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
create policy update_rows on public.issues for update to authenticated using(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id)) with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
alter table public.issues add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.decisions (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, name text not null, context text not null, alternatives text not null, approver_id uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.decisions(tenant_id,created_at);
alter table public.decisions enable row level security;
create trigger touch before insert or update on public.decisions for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.decisions for each row execute function public.audit_change();
create policy read_rows on public.decisions for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
create policy insert_rows on public.decisions for insert to authenticated with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
create policy update_rows on public.decisions for update to authenticated using(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id)) with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
alter table public.decisions add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.change_requests (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, name text not null, hours numeric(8,2) not null check(hours>=0), cost numeric(16,2) not null check(cost>=0), impact text not null, status text not null default 'pending', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.change_requests(tenant_id,created_at);
alter table public.change_requests enable row level security;
create trigger touch before insert or update on public.change_requests for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.change_requests for each row execute function public.audit_change();
create policy read_rows on public.change_requests for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
create policy insert_rows on public.change_requests for insert to authenticated with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
create policy update_rows on public.change_requests for update to authenticated using(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id)) with check(public.allowed(tenant_id,'projects',true) and public.scoped(tenant_id,project_id));
alter table public.change_requests add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.absences (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, user_id uuid not null references auth.users, name text not null, starts_on date not null, ends_on date not null, hours numeric(8,2) not null check(hours>0), check(ends_on>=starts_on), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.absences(tenant_id,created_at);
alter table public.absences enable row level security;
create trigger touch before insert or update on public.absences for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.absences for each row execute function public.audit_change();
create policy read_rows on public.absences for select to authenticated using(public.allowed(tenant_id,'work'));
create policy insert_rows on public.absences for insert to authenticated with check(public.allowed(tenant_id,'work',true) and user_id=auth.uid());
create policy update_rows on public.absences for update to authenticated using(public.allowed(tenant_id,'work',true) and user_id=auth.uid()) with check(public.allowed(tenant_id,'work',true) and user_id=auth.uid());

create table public.capacity_calendar (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, user_id uuid not null references auth.users, name text not null, week_start date not null, hours numeric(8,2) not null check(hours>=0), unique(tenant_id,user_id,week_start), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.capacity_calendar(tenant_id,created_at);
alter table public.capacity_calendar enable row level security;
create trigger touch before insert or update on public.capacity_calendar for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.capacity_calendar for each row execute function public.audit_change();
create policy read_rows on public.capacity_calendar for select to authenticated using(public.allowed(tenant_id,'work'));
create policy insert_rows on public.capacity_calendar for insert to authenticated with check(public.allowed(tenant_id,'work',true) and user_id=auth.uid());
create policy update_rows on public.capacity_calendar for update to authenticated using(public.allowed(tenant_id,'work',true) and user_id=auth.uid()) with check(public.allowed(tenant_id,'work',true) and user_id=auth.uid());

create table public.files (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, name text not null, storage_path text not null, hash text not null, version integer not null default 1, shared boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.files(tenant_id,created_at);
alter table public.files enable row level security;
create trigger touch before insert or update on public.files for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.files for each row execute function public.audit_change();
create policy read_rows on public.files for select to authenticated using(public.allowed(tenant_id,'files') and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=files.tenant_id and m.user_id=auth.uid() and m.role='client') or shared));
create policy insert_rows on public.files for insert to authenticated with check(public.allowed(tenant_id,'files',true) and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=files.tenant_id and m.user_id=auth.uid() and m.role='client') or shared));
create policy update_rows on public.files for update to authenticated using(public.allowed(tenant_id,'files',true) and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=files.tenant_id and m.user_id=auth.uid() and m.role='client') or shared)) with check(public.allowed(tenant_id,'files',true) and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=files.tenant_id and m.user_id=auth.uid() and m.role='client') or shared));
alter table public.files add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.comments (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, file_id uuid not null, name text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.comments(tenant_id,created_at);
alter table public.comments enable row level security;
create trigger touch before insert or update on public.comments for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.comments for each row execute function public.audit_change();
create policy read_rows on public.comments for select to authenticated using(public.allowed(tenant_id,'files') and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=comments.tenant_id and m.user_id=auth.uid() and m.role='client') or exists(select 1 from public.files f where f.id=file_id and f.shared)));
create policy insert_rows on public.comments for insert to authenticated with check(public.allowed(tenant_id,'files',true) and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=comments.tenant_id and m.user_id=auth.uid() and m.role='client') or exists(select 1 from public.files f where f.id=file_id and f.shared)));
create policy update_rows on public.comments for update to authenticated using(public.allowed(tenant_id,'files',true) and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=comments.tenant_id and m.user_id=auth.uid() and m.role='client') or exists(select 1 from public.files f where f.id=file_id and f.shared))) with check(public.allowed(tenant_id,'files',true) and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=comments.tenant_id and m.user_id=auth.uid() and m.role='client') or exists(select 1 from public.files f where f.id=file_id and f.shared)));
alter table public.comments add foreign key(tenant_id,file_id) references public.files(tenant_id,id);
alter table public.comments add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

create table public.approvals (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.organizations_internal, project_id uuid not null, file_id uuid not null, name text not null, status text not null default 'pending' check(status in ('pending','approved','rejected')), internal boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users default auth.uid(), archived_at timestamptz, unique(tenant_id,id));
create index on public.approvals(tenant_id,created_at);
alter table public.approvals enable row level security;
create trigger touch before insert or update on public.approvals for each row execute function public.touch_record();
create trigger audit after insert or update or delete on public.approvals for each row execute function public.audit_change();
create policy read_rows on public.approvals for select to authenticated using(public.allowed(tenant_id,'files') and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=approvals.tenant_id and m.user_id=auth.uid() and m.role='client') or exists(select 1 from public.files f where f.id=file_id and f.shared)));
create policy insert_rows on public.approvals for insert to authenticated with check(public.allowed(tenant_id,'files',true) and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=approvals.tenant_id and m.user_id=auth.uid() and m.role='client') or exists(select 1 from public.files f where f.id=file_id and f.shared)));
create policy update_rows on public.approvals for update to authenticated using(public.allowed(tenant_id,'files',true) and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=approvals.tenant_id and m.user_id=auth.uid() and m.role='client') or exists(select 1 from public.files f where f.id=file_id and f.shared))) with check(public.allowed(tenant_id,'files',true) and public.scoped(tenant_id,project_id) and (not exists(select 1 from public.memberships m where m.tenant_id=approvals.tenant_id and m.user_id=auth.uid() and m.role='client') or exists(select 1 from public.files f where f.id=file_id and f.shared)));
alter table public.approvals add foreign key(tenant_id,file_id) references public.files(tenant_id,id);
alter table public.approvals add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);

alter table public.project_members add foreign key(tenant_id,project_id) references public.projects(tenant_id,id);
alter table public.organizations_internal enable row level security;
alter table public.memberships enable row level security;
alter table public.project_members enable row level security;
alter table public.permissions enable row level security;
alter table public.audit_events enable row level security;
create policy own_tenants on public.organizations_internal for select to authenticated using(exists(select 1 from public.memberships m where m.tenant_id=organizations_internal.id and m.user_id=auth.uid() and m.active));
create policy own_membership on public.memberships for select to authenticated using(user_id=auth.uid());
create policy project_member_read on public.project_members for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
create policy project_member_write on public.project_members for insert to authenticated with check(public.allowed(tenant_id,'admin',true) and public.scoped(tenant_id,project_id));
create policy permission_read on public.permissions for select to authenticated using(true);
create policy audit_read on public.audit_events for select to authenticated using(public.allowed(tenant_id,'admin') or exists(select 1 from public.memberships m where m.tenant_id=audit_events.tenant_id and m.user_id=auth.uid() and m.role='auditor' and m.active));
grant usage on schema public to authenticated;
grant select,insert,update on all tables in schema public to authenticated;
revoke insert,update on public.audit_events,public.memberships,public.permissions,public.organizations_internal from authenticated;


insert into supabase_migrations.schema_migrations(version,name) values('202610050001','foundation');

-- Migration: 202610050002_transactions.sql

create function public.require_access(t uuid,d text,p uuid default null) returns void language plpgsql security definer set search_path='' as $$ begin
 if not public.allowed(t,d,true) or (p is not null and not public.scoped(t,p)) then raise exception 'permission denied' using errcode='42501'; end if;
end; $$;
create function public.create_lead(t uuid,company text,contact text,email text,need text,source text,next_action text) returns uuid language plpgsql security definer set search_path='' as $$
declare a uuid;c uuid;l uuid;
begin
 perform public.require_access(t,'crm');
 if length(trim(company))<2 or length(trim(contact))<2 or email not like '%@%.%' or length(trim(need))<3 or length(trim(source))<2 or length(trim(next_action))<2 then raise exception 'invalid lead'; end if;
 insert into public.accounts(tenant_id,name) values(t,trim(company)) returning id into a;
 insert into public.contacts(tenant_id,account_id,name,email) values(t,a,trim(contact),lower(trim(email))) returning id into c;
 insert into public.leads(tenant_id,account_id,contact_id,name,source,need,owner_id,next_action) values(t,a,c,company,source,need,auth.uid(),next_action) returning id into l;
 return l;
end; $$;
create function public.qualify_lead(t uuid,l uuid,service text,amount numeric,close_date date) returns uuid language plpgsql security definer set search_path='' as $$
declare lead public.leads;o uuid;
begin
 perform public.require_access(t,'crm');
 select * into strict lead from public.leads where id=l and tenant_id=t for update;
 select id into o from public.opportunities where tenant_id=t and lead_id=l;
 if o is not null then return o; end if;
 if amount<=0 or length(trim(service))<2 or close_date is null then raise exception 'invalid opportunity'; end if;
 insert into public.opportunities(tenant_id,lead_id,account_id,contact_id,name,service,amount,owner_id,next_action,close_date) values(t,l,lead.account_id,lead.contact_id,lead.name,service,amount,lead.owner_id,lead.next_action,close_date) returning id into o;
 insert into public.opportunity_stage_history(tenant_id,opportunity_id,to_stage,reason) values(t,o,'Qualified','Lead calificado');
 update public.leads set status='converted' where id=l;
 return o;
end; $$;
create function public.create_proposal(t uuid,o uuid,scope text,valid_until date) returns uuid language plpgsql security definer set search_path='' as $$
declare opp public.opportunities;p uuid;
begin
 perform public.require_access(t,'crm');
 select * into strict opp from public.opportunities where id=o and tenant_id=t for update;
 if opp.stage in ('Won','Lost') or length(trim(scope))<5 or valid_until<current_date then raise exception 'invalid proposal'; end if;
 insert into public.proposals(tenant_id,opportunity_id,name,scope,amount,version,valid_until,approved) values(t,o,'Propuesta · '||opp.name,scope,opp.amount,(select coalesce(max(version),0)+1 from public.proposals where opportunity_id=o),valid_until,true) returning id into p;
 return p;
end; $$;
create function public.advance_opportunity(t uuid,o uuid,target text,reason text) returns uuid language plpgsql security definer set search_path='' as $$
declare opp public.opportunities;p uuid;c uuid;proposal public.proposals;n integer;sequence text[]:=array['Qualified','Discovery','Solution Designed','Proposal Sent','Negotiation','Won'];
begin
 perform public.require_access(t,'crm');
 select * into strict opp from public.opportunities where id=o and tenant_id=t for update;
 if target='Won' and opp.stage='Won' then select id into p from public.projects where tenant_id=t and opportunity_id=o; return p; end if;
 if opp.stage in ('Won','Lost') or length(trim(reason))<3 then raise exception 'closed opportunity or reason missing'; end if;
 if target!='Lost' and array_position(sequence,target) is distinct from array_position(sequence,opp.stage)+1 then raise exception 'invalid stage transition'; end if;
 if target in ('Proposal Sent','Negotiation','Won') then
 select * into proposal from public.proposals where tenant_id=t and opportunity_id=o and approved and valid_until>=current_date order by version desc limit 1;
 if proposal.id is null then raise exception 'approved valid proposal required'; end if;
 end if;
 update public.opportunities set stage=target,probability=case target when 'Won' then 100 when 'Lost' then 0 when 'Discovery' then 35 when 'Solution Designed' then 50 when 'Proposal Sent' then 65 when 'Negotiation' then 85 else probability end,lost_reason=case when target='Lost' then reason end where id=o;
 insert into public.opportunity_stage_history(tenant_id,opportunity_id,from_stage,to_stage,reason) values(t,o,opp.stage,target,reason);
 if target='Won' then
 update public.accounts set relationship='client' where id=opp.account_id and tenant_id=t;
 insert into public.contracts(tenant_id,opportunity_id,account_id,name,scope,fee,currency) values(t,o,opp.account_id,'Contrato · '||opp.name,proposal.scope,proposal.amount,opp.currency) returning id into c;
 insert into public.projects(tenant_id,opportunity_id,account_id,contract_id,name,owner_id,fee,budget,currency) values(t,o,opp.account_id,c,opp.name,opp.owner_id,proposal.amount,round(proposal.amount*0.7,2),opp.currency) returning id into p;
 insert into public.project_members(tenant_id,project_id,user_id) values(t,p,opp.owner_id);
 insert into public.project_budgets(tenant_id,project_id,name,amount) values(t,p,'Baseline v1',round(proposal.amount*0.7,2));
 for n in 1..6 loop
 insert into public.phases(tenant_id,project_id,position,name,gate_criteria) values(t,p,n,(array['Diagnóstico inicial','Diseño del estudio','Levantamiento','Análisis estratégico','Priorización','Presentación ejecutiva'])[n],(array['Problem statement, sponsor, decisión objetivo y fuentes aprobados','Scope baseline, cronograma, presupuesto e instrumento aprobados','Muestra cerrada, evidencias y QA completos','Dataset congelado y hallazgos revisados','Matriz, responsables, impacto y riesgos revisados','Entregables aprobados, sesión y acta de decisiones'])[n]);
 end loop;
 insert into public.notifications(tenant_id,project_id,user_id,name) values(t,p,opp.owner_id,'Proyecto creado desde oportunidad ganada');
 end if;
 return coalesce(p,o);
end; $$;
create function public.record_time(t uuid,task uuid,minutes integer,work_date date,billable boolean,description text) returns uuid language plpgsql security definer set search_path='' as $$
declare item public.tasks;rate numeric;entry uuid;
begin
 select * into strict item from public.tasks where id=task and tenant_id=t;
 perform public.require_access(t,'work',item.project_id);
 if not exists(select 1 from public.project_members where tenant_id=t and project_id=item.project_id and user_id=auth.uid()) then raise exception 'project membership required' using errcode='42501'; end if;
 select cost_per_hour into rate from public.role_cost_rates where tenant_id=t and user_id=auth.uid() and effective_from<=work_date order by effective_from desc limit 1;
 if rate is null then raise exception 'effective cost rate missing'; end if;
 if length(trim(description))<3 then raise exception 'description required'; end if;
 insert into public.time_entries(tenant_id,project_id,task_id,user_id,name,minutes,billable,work_date,hourly_cost) values(t,item.project_id,task,auth.uid(),description,minutes,billable,work_date,rate) returning id into entry;
 return entry;
end; $$;
create function public.issue_invoice(t uuid,p uuid,concept text,subtotal numeric,tax numeric,due date) returns uuid language plpgsql security definer set search_path='' as $$
declare project public.projects;i uuid;
begin
 perform public.require_access(t,'finance',p);
 select * into strict project from public.projects where tenant_id=t and id=p;
 if length(trim(concept))<3 then raise exception 'concept required'; end if;
 insert into public.invoices(tenant_id,project_id,account_id,name,subtotal,tax,currency,issued_on,due_date) values(t,p,project.account_id,concept,subtotal,tax,project.currency,current_date,due) returning id into i;
 return i;
end; $$;
create function public.record_payment(t uuid,i uuid,amount numeric,paid_on date,method text,reference text,key uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare invoice public.invoices;paid numeric;p uuid;existing public.payments;
begin
 perform public.require_access(t,'finance');
 select * into strict invoice from public.invoices where id=i and tenant_id=t for update;
 select * into existing from public.payments where tenant_id=t and idempotency_key=key;
 if existing.id is not null then
 if existing.invoice_id!=i or existing.amount!=amount or existing.paid_on!=paid_on or existing.method!=method or existing.reference!=reference then raise exception 'idempotency key conflict'; end if;
 return existing.id;
 end if;
 if length(trim(method))<2 or length(trim(reference))<2 or amount<=0 or paid_on>current_date then raise exception 'invalid payment'; end if;
 select coalesce(sum(x.amount),0) into paid from public.payments x where x.invoice_id=i;
 if paid+amount>invoice.subtotal+invoice.tax then raise exception 'payment exceeds outstanding balance'; end if;
 insert into public.payments(tenant_id,project_id,invoice_id,name,amount,paid_on,method,reference,idempotency_key) values(t,invoice.project_id,i,'Pago · '||reference,amount,paid_on,method,reference,key) returning id into p;
 update public.invoices set status=case when paid+amount=invoice.subtotal+invoice.tax then 'paid' else 'partial' end where id=i;
 return p;
end; $$;
-- Invoker views preserve row-level security. No cross-currency sums.
create view public.invoice_balances with(security_invoker=true) as
select i.*,coalesce(p.paid,0) paid,i.subtotal+i.tax-coalesce(p.paid,0) balance,greatest(current_date-i.due_date,0) days_overdue
from public.invoices i left join (select invoice_id,sum(amount) paid from public.payments group by invoice_id) p on p.invoice_id=i.id;
create view public.project_profitability with(security_invoker=true) as
select p.id,p.tenant_id,p.name,p.currency,p.fee,p.budget,p.costs_complete,
 coalesce(t.cost,0)+coalesce(e.cost,0) direct_cost,
 case when p.costs_complete and p.fee>0 then round((p.fee-coalesce(t.cost,0)-coalesce(e.cost,0))/p.fee*100,2) end margin_percent
from public.projects p left join(select project_id,sum(minutes::numeric/60*hourly_cost) cost from public.time_entries group by project_id)t on t.project_id=p.id
left join(select project_id,sum(amount) cost from public.expenses where status='approved' group by project_id)e on e.project_id=p.id;
create function public.command_kpis(t uuid,start_on date,end_on date,money text default 'MXN') returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare result jsonb;
begin
 if not public.allowed(t,'finance') then raise exception 'finance permission required' using errcode='42501'; end if;
 if end_on<start_on then raise exception 'invalid date range'; end if;
 select jsonb_build_object(
 'invoiced',coalesce((select sum(subtotal) from public.invoices where tenant_id=t and currency=money and issued_on between start_on and end_on),0),
 'collections',coalesce((select sum(p.amount) from public.payments p join public.invoices i on i.id=p.invoice_id where p.tenant_id=t and i.currency=money and p.paid_on between start_on and end_on),0),
 'receivables',coalesce((select sum(balance) from public.invoice_balances where tenant_id=t and currency=money),0),
 'overdue',coalesce((select sum(balance) from public.invoice_balances where tenant_id=t and currency=money and due_date<current_date),0),
 'pipeline',case when public.allowed(t,'crm') then coalesce((select sum(amount*probability/100) from public.opportunities where tenant_id=t and currency=money and stage not in ('Won','Lost') and close_date between start_on and end_on),0) else null end,
 'active_projects',(select count(*) from public.projects where tenant_id=t and currency=money and status='active'),
 'hours',coalesce((select sum(e.minutes)::numeric/60 from public.time_entries e join public.projects p on p.id=e.project_id where e.tenant_id=t and p.currency=money and work_date between start_on and end_on),0),
 'direct_cost',coalesce((select sum(direct_cost) from public.project_profitability where tenant_id=t and currency=money),0)
 ) into result;
 return result;
end; $$;
grant select on public.invoice_balances,public.project_profitability to authenticated;
-- Functions are inaccessible anonymously; every security-definer RPC checks membership.
revoke execute on all functions in schema public from public,anon;
grant execute on all functions in schema public to authenticated;


insert into supabase_migrations.schema_migrations(version,name) values('202610050002','transactions');

-- Migration: 202610050003_invariants.sql

-- Lock immutable business transitions behind the transactional RPC API.
drop policy if exists insert_rows on public.opportunities;
drop policy if exists update_rows on public.opportunities;
drop policy if exists insert_rows on public.leads;
drop policy if exists update_rows on public.leads;
create function public.guard_update() returns trigger language plpgsql set search_path='' as $$ begin
 if new.tenant_id<>old.tenant_id or new.id<>old.id or new.created_by is distinct from old.created_by or new.created_at<>old.created_at then raise exception 'immutable identity fields'; end if;
 if tg_table_name='projects' and (to_jsonb(new)->'fee' is distinct from to_jsonb(old)->'fee' or to_jsonb(new)->'budget' is distinct from to_jsonb(old)->'budget' or to_jsonb(new)->'costs_complete' is distinct from to_jsonb(old)->'costs_complete') and auth.uid() is not null and not public.allowed(new.tenant_id,'finance',true) then raise exception 'finance permission required' using errcode='42501'; end if;
 return new;
end; $$;
do $$ declare t text;begin for t in select c.table_name from information_schema.columns c join information_schema.tables t on t.table_schema=c.table_schema and t.table_name=c.table_name where c.table_schema='public' and c.column_name='updated_at' and t.table_type='BASE TABLE' loop execute format('create trigger guard_update before update on public.%I for each row execute function public.guard_update()',t);end loop;end;$$;
create function public.guard_member_owner() returns trigger language plpgsql security definer set search_path='' as $$
declare u uuid; begin
 u=coalesce((to_jsonb(new)->>'owner_id')::uuid,(to_jsonb(new)->>'user_id')::uuid);
 if u is not null and not exists(select 1 from public.memberships where tenant_id=new.tenant_id and user_id=u and active) then raise exception 'owner must belong to tenant'; end if;
 return new;
end;$$;
do $$ declare t text;begin foreach t in array array['leads','opportunities','projects','tasks','risks','project_members','role_cost_rates','time_entries','absences','capacity_calendar'] loop execute format('create trigger guard_member before insert or update on public.%I for each row execute function public.guard_member_owner()',t);end loop;end;$$;
-- A task/phase or time entry cannot point to a different project in the same tenant.
alter table public.tasks add unique(tenant_id,project_id,id);
alter table public.phases add unique(tenant_id,project_id,id);
alter table public.tasks add foreign key(tenant_id,project_id,phase_id) references public.phases(tenant_id,project_id,id);
alter table public.time_entries add foreign key(tenant_id,project_id,task_id) references public.tasks(tenant_id,project_id,id);
alter table public.invoices add unique(tenant_id,project_id,id);
alter table public.payments add foreign key(tenant_id,project_id,invoice_id) references public.invoices(tenant_id,project_id,id);
create function public.no_audit_mutation() returns trigger language plpgsql set search_path='' as $$ begin raise exception 'audit is append-only'; end; $$;
create trigger append_only before update or delete on public.audit_events for each row execute function public.no_audit_mutation();
create trigger audit after insert or update or delete on public.memberships for each row execute function public.audit_change();
create trigger audit after insert or update or delete on public.project_members for each row execute function public.audit_change();
create or replace view public.project_profitability with(security_invoker=true) as
select p.id,p.tenant_id,p.name,p.currency,p.fee,p.budget,p.costs_complete,
 coalesce(t.cost,0)+coalesce(e.cost,0) direct_cost,
 case when p.costs_complete and p.fee>0 then round((p.fee-coalesce(t.cost,0)-coalesce(e.cost,0))/p.fee*100,2) end margin_percent,p.created_at
from public.projects p left join(select project_id,sum(minutes::numeric/60*hourly_cost) cost from public.time_entries group by project_id)t on t.project_id=p.id
left join(select project_id,sum(amount) cost from public.expenses where status='approved' group by project_id)e on e.project_id=p.id;
revoke execute on all functions in schema public from public,anon;
grant execute on all functions in schema public to authenticated;


insert into supabase_migrations.schema_migrations(version,name) values('202610050003','invariants');

-- Migration: 202610050004_operations_finance.sql

create table public.phase_gate_reviews (
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.organizations_internal,
 project_id uuid not null,phase_id uuid not null,name text not null,evidence text not null check(length(evidence)>=10),
 approved_by uuid not null references auth.users,created_by uuid references auth.users default auth.uid(),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,
 foreign key(tenant_id,project_id,phase_id) references public.phases(tenant_id,project_id,id),unique(phase_id)
);
alter table public.phase_gate_reviews enable row level security;
create policy gate_read on public.phase_gate_reviews for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id));
grant select on public.phase_gate_reviews to authenticated;
create trigger audit after insert on public.phase_gate_reviews for each row execute function public.audit_change();
-- Direct writes cannot bypass the gate transaction.
drop policy insert_rows on public.phases;
drop policy update_rows on public.phases;
create function public.approve_gate(t uuid,p uuid,evidence text) returns uuid language plpgsql security definer set search_path='' as $$
declare phase public.phases;r uuid;
begin
 select * into strict phase from public.phases where tenant_id=t and id=p for update;
 perform public.require_access(t,'projects',phase.project_id);
 if not exists(select 1 from public.memberships where tenant_id=t and user_id=auth.uid() and role in ('owner','operations','pm') and active) then raise exception 'reviewer permission required' using errcode='42501'; end if;
 if length(trim(evidence))<10 then raise exception 'gate evidence required'; end if;
 if exists(select 1 from public.phases where tenant_id=t and project_id=phase.project_id and position<phase.position and approved_at is null) then raise exception 'previous gates incomplete'; end if;
 select id into r from public.phase_gate_reviews where phase_id=p;
 if r is not null then return r; end if;
 insert into public.phase_gate_reviews(tenant_id,project_id,phase_id,name,evidence,approved_by) values(t,phase.project_id,p,'Gate aprobado: '||phase.name,evidence,auth.uid()) returning id into r;
 update public.phases set approved_at=now(),approved_by=auth.uid() where id=p;
 return r;
end;$$;
create function public.approve_expense(t uuid,e uuid,approved boolean) returns uuid language plpgsql security definer set search_path='' as $$
declare expense public.expenses;
begin
 perform public.require_access(t,'finance');select * into strict expense from public.expenses where tenant_id=t and id=e for update;
 if expense.status!='pending' then raise exception 'expense already reviewed'; end if;
 update public.expenses set status=case when approved then 'approved' else 'rejected' end where id=e;
 return e;
end;$$;
-- Status may only be changed by the approval RPC (definer), not a direct REST edit.
drop policy update_rows on public.expenses;
drop policy insert_rows on public.expenses;
create policy expense_draft on public.expenses for insert to authenticated with check(public.allowed(tenant_id,'finance',true) and public.scoped(tenant_id,project_id) and status='pending');
create function public.set_cost_rate(t uuid,u uuid,rate numeric,effective date) returns uuid language plpgsql security definer set search_path='' as $$
declare r uuid;begin
 perform public.require_access(t,'finance');
 insert into public.role_cost_rates(tenant_id,user_id,cost_per_hour,effective_from) values(t,u,rate,effective) returning id into r;return r;
end;$$;
drop policy update_rows on public.role_cost_rates;
create function public.attest_costs(t uuid,p uuid,complete boolean) returns uuid language plpgsql security definer set search_path='' as $$
begin perform public.require_access(t,'finance',p);update public.projects set costs_complete=complete where id=p and tenant_id=t;if not found then raise exception 'project not found';end if;return p;end;$$;
create view public.ar_aging with(security_invoker=true) as
select tenant_id,currency,
 sum(balance) filter(where days_overdue=0) current_balance,
 sum(balance) filter(where days_overdue between 1 and 30) overdue_1_30,
 sum(balance) filter(where days_overdue between 31 and 60) overdue_31_60,
 sum(balance) filter(where days_overdue between 61 and 90) overdue_61_90,
 sum(balance) filter(where days_overdue>90) overdue_90_plus
from public.invoice_balances where balance>0 group by tenant_id,currency;
create view public.capacity_summary with(security_invoker=true) as
select c.id,c.tenant_id,c.user_id,c.name,c.week_start,c.created_at,c.hours available_hours,
 coalesce(a.absent_hours,0) absent_hours,
 greatest(c.hours-coalesce(a.absent_hours,0),0) net_hours,
 coalesce(t.planned_hours,0) planned_hours,coalesce(e.actual_hours,0) actual_hours
from public.capacity_calendar c
left join lateral(select sum(hours * (least(ends_on,c.week_start+6)-greatest(starts_on,c.week_start)+1)::numeric/(ends_on-starts_on+1)) absent_hours from public.absences where tenant_id=c.tenant_id and user_id=c.user_id and starts_on<=c.week_start+6 and ends_on>=c.week_start)a on true
left join lateral(select sum(estimated_hours) planned_hours from public.tasks where tenant_id=c.tenant_id and owner_id=c.user_id and due_date between c.week_start and c.week_start+6 and status!='done')t on true
left join lateral(select sum(minutes)::numeric/60 actual_hours from public.time_entries where tenant_id=c.tenant_id and user_id=c.user_id and work_date between c.week_start and c.week_start+6)e on true;
grant select on public.ar_aging,public.capacity_summary to authenticated;
revoke execute on all functions in schema public from public,anon;
grant execute on all functions in schema public to authenticated;


insert into supabase_migrations.schema_migrations(version,name) values('202610050004','operations_finance');

-- Migration: 202610050005_identity.sql

create function public.assign_membership(t uuid,u uuid,r public.app_role) returns uuid language plpgsql security definer set search_path='' as $$
declare member uuid;begin
 perform public.require_access(t,'admin');
 insert into public.memberships(tenant_id,user_id,role) values(t,u,r) on conflict(tenant_id,user_id) do update set role=excluded.role,active=true returning id into member;
 return member;
end;$$;
create function public.assign_project_member(t uuid,p uuid,u uuid) returns uuid language plpgsql security definer set search_path='' as $$
declare member uuid;begin
 perform public.require_access(t,'projects',p);
 if not exists(select 1 from public.memberships where tenant_id=t and user_id=auth.uid() and role in ('owner','operations','pm') and active) then raise exception 'assignment permission required' using errcode='42501';end if;
 insert into public.project_members(tenant_id,project_id,user_id) values(t,p,u) on conflict(project_id,user_id) do update set user_id=excluded.user_id returning id into member;
 return member;
end;$$;
alter table public.files add unique(tenant_id,project_id,id);
alter table public.comments add foreign key(tenant_id,project_id,file_id) references public.files(tenant_id,project_id,id);
alter table public.approvals add foreign key(tenant_id,project_id,file_id) references public.files(tenant_id,project_id,id);
revoke execute on all functions in schema public from public,anon;
grant execute on all functions in schema public to authenticated;


insert into supabase_migrations.schema_migrations(version,name) values('202610050005','identity');

-- Migration: 202610050006_tenant_identity.sql

drop policy own_tenants on public.organizations_internal;
create policy own_tenants on public.organizations_internal for select to authenticated using(exists(select 1 from public.memberships m where m.tenant_id=organizations_internal.id and m.user_id=auth.uid() and m.active));
drop policy own_membership on public.memberships;
create policy own_membership on public.memberships for select to authenticated using(user_id=auth.uid() or public.allowed(tenant_id,'admin'));


insert into supabase_migrations.schema_migrations(version,name) values('202610050006','tenant_identity');

-- Migration: 202610050007_members.sql

create function public.manage_member(t uuid,u uuid,r public.app_role,enabled boolean) returns uuid language plpgsql security definer set search_path='' as $$
declare m public.memberships;begin
 perform public.require_access(t,'admin');
 select * into strict m from public.memberships where tenant_id=t and user_id=u for update;
 if m.role='owner' and (r!='owner' or not enabled) and (select count(*) from public.memberships where tenant_id=t and role='owner' and active)<=1 then raise exception 'cannot remove last active owner';end if;
 update public.memberships set role=r,active=enabled where id=m.id;return m.id;
end;$$;
revoke execute on function public.manage_member(uuid,uuid,public.app_role,boolean) from public,anon;
grant execute on function public.manage_member(uuid,uuid,public.app_role,boolean) to authenticated;


insert into supabase_migrations.schema_migrations(version,name) values('202610050007','members');

-- Migration: 202610050008_owner_guard.sql

create function public.guard_last_owner() returns trigger language plpgsql security definer set search_path='' as $$
begin
 if old.role='owner' and old.active and (new.role!='owner' or not new.active) then
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(old.tenant_id::text,0));
 if not exists(select 1 from public.memberships where tenant_id=old.tenant_id and role='owner' and active and id!=old.id) then raise exception 'cannot remove last active owner';end if;
 end if;return new;
end;$$;
create trigger guard_last_owner before update on public.memberships for each row execute function public.guard_last_owner();
revoke execute on function public.guard_last_owner() from public,anon;
grant execute on function public.guard_last_owner() to authenticated;


insert into supabase_migrations.schema_migrations(version,name) values('202610050008','owner_guard');

-- Migration: 202610050009_health.sql

create function public.database_health() returns boolean language sql stable security invoker set search_path='' as $$ select true $$;
grant usage on schema public to anon;
grant execute on function public.database_health() to anon,authenticated,service_role;


insert into supabase_migrations.schema_migrations(version,name) values('202610050009','health');

-- Migration: 202610050010_external_boundary.sql

-- Until the scoped Portal is implemented, guests never read internal project/budget rows.
delete from public.permissions where role='client' and domain='projects';
create function public.is_client(t uuid) returns boolean language sql stable security definer set search_path='' as $$
 select exists(select 1 from public.memberships where tenant_id=t and user_id=auth.uid() and role='client' and active);
$$;
alter table public.comments add column internal boolean not null default true;
drop policy read_rows on public.comments;
create policy read_rows on public.comments for select to authenticated using(public.allowed(tenant_id,'files') and public.scoped(tenant_id,project_id) and (not public.is_client(tenant_id) or (not internal and exists(select 1 from public.files f where f.id=comments.file_id and f.shared))));
drop policy read_rows on public.approvals;
create policy read_rows on public.approvals for select to authenticated using(public.allowed(tenant_id,'files') and public.scoped(tenant_id,project_id) and (not public.is_client(tenant_id) or (not internal and exists(select 1 from public.files f where f.id=approvals.file_id and f.shared))));
drop policy read_rows on public.notifications;
create policy read_rows on public.notifications for select to authenticated using(public.allowed(tenant_id,'projects') and public.scoped(tenant_id,project_id) and (user_id=auth.uid() or public.allowed(tenant_id,'admin')));
revoke execute on function public.is_client(uuid) from public,anon;
grant execute on function public.is_client(uuid) to authenticated;


insert into supabase_migrations.schema_migrations(version,name) values('202610050010','external_boundary');

notify pgrst, 'reload schema';

commit;

select 'AUREX schema ready' as result;
